### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by neojski** [Amanite/ocamlpics#1]
`triangles.ml` throws syntax error

```
File "triangles.ml", line 97, characters 2-6:
Error: Syntax error
```

and it's because there should be `begin` and `end` around `if` body (and `else` body). After fixing that it does not complie because `squared256` is not defined.

**Comment by Amanite** [comment]
Whoops, sorry, this was a mistake on my end, fixed now ; feel free to tell me if anything doesn't work as expected.

**Comment by neojski** [comment]
Did I mention it's the same for dots?

**Comment by Amanite** [comment]
Okay now everything should be working properly.

**Comment by neojski** [comment]
Indeed it compiles now. Thanks.
